### ISSUE TITLE
Unable to access callee of strict mode function

### ISSUE THREAD

**Issue by chrisbuttery** [babel/duo-babel#3]
Hi there, when using duo-babel to build my tests - in conjunction with the Chai ‘Expect’ assertion style - I get the following error:

```
TypeError: Unable to access callee of strict mode function
```

You can test it out in this example repo: https://github.com/chrisbuttery/duo-test-babel

By swapping out the build task in the Makefile you can see it only throws the error when using duo-babel.

**Comment by chrisbuttery** [comment]
As this is just a plugin for `babel-core` - I'm not sure if I should raise the issue over there?

**Comment by sebmck** [comment]
This is expected behaviour. ES6 modules have an implicit strict mode and in strict mode, as the error says, `arguments.callee` is unavailable. You _[can](http://babeljs.io/docs/usage/transformers/other/strict/#blacklisting)_ disable it although I'd highly discourage it for the reasons outlined on that page and it likely shadows another larger problem which is that you're probably transforming `node_modules` as `chai` shouldn't even be touched by Babel.
